export default [
  {
    files: ["**/*.js"],
    ignores: [
      "IVG/**",
      "Synplant Resources/**",
      "CushyLint/**",
      "tools/IVG2PNG/**",
      "tools/jsconsole-bridge-mcp/**"
    ],
    languageOptions: {
      ecmaVersion: 5,
      sourceType: "script",
      globals: {
        // Standard ES5 additions that NuXJS/Synplant scripts may use.
        JSON: "readonly",

        // Native API and constants from ts/COJSEngine.d.ts.
        BRANCH_COUNT: "readonly",
        CONTROLS: "readonly",
        DIR_SLASH: "readonly",
        GENES: "readonly",
        GROWABLE_GENE_COUNT: "readonly",
        PARAMS: "readonly",
        PARAM_INDEXES: "readonly",
        PROGRAM_COUNT: "readonly",
        analyzePatchAudio: "readonly",
        ask: "readonly",
        browse: "readonly",
        composeNumbstrict: "readonly",
        copyFile: "readonly",
        createElement: "readonly",
        deriveOpenPatchDir: "readonly",
        dir: "readonly",
        display: "readonly",
        editCushyVariable: "readonly",
        editParam: "readonly",
        eraseFile: "readonly",
        fileInfo: "readonly",
        fullPath: "readonly",
        gc: "readonly",
        getCushyVariable: "readonly",
        getElement: "readonly",
        getElementId: "readonly",
        getMonotonicTime: "readonly",
        getParam: "readonly",
        handleCushyPreparation: "writable",
        handleCushyTrace: "writable",
        isMarshaledFormat: "readonly",
        load: "readonly",
        makeDir: "readonly",
        marshal: "readonly",
        moveFile: "readonly",
        papageno: "readonly",
        paramText: "readonly",
        paramValue: "readonly",
        parseNumbstrict: "readonly",
        performCushyAction: "readonly",
        print: "writable",
        readClipboard: "readonly",
        run: "readonly",
        save: "readonly",
        saveUndo: "readonly",
        sendMidi: "readonly",
        setCushyVariable: "readonly",
        setElement: "readonly",
        setParam: "readonly",
        setPreview: "readonly",
        spawnPatch: "readonly",
        splitPath: "readonly",
        translate: "readonly",
        unmarshal: "readonly",
        writeClipboard: "readonly",

        // Host helper layer from Synplant Resources/Synplant2_main.js and the
        // JS Reference's Host Script Helpers section.
        BUILD: "readonly",
        Color: "readonly",
        ComputedGUIVariable: "readonly",
        DIRS: "readonly",
        Filtered: "readonly",
        PLATFORM: "readonly",
        StringBuilder: "readonly",
        Xorshift: "readonly",
        addModPatcher: "readonly",
        assert: "readonly",
        bisect: "readonly",
        bounce: "readonly",
        calcPostSoftClipGain: "readonly",
        calcPreSoftClipGain: "readonly",
        calcPreSoftClipParam: "readonly",
        calcVolumeGain: "readonly",
        calcVolumeParam: "readonly",
        clamp: "readonly",
        closeCushy: "readonly",
        createClass: "readonly",
        cube: "readonly",
        deepClone: "readonly",
        displayCushy: "readonly",
        displayHint: "readonly",
        exp2: "readonly",
        floorMod: "readonly",
        fract: "readonly",
        fromDecibel: "readonly",
        getCachedPatch: "readonly",
        getDisplayedCushy: "readonly",
        globals: "readonly",
        inverseSignedSquare: "readonly",
        isRepeating: "readonly",
        lerp: "readonly",
        loadPatch: "readonly",
        loadSynplantPatch: "readonly",
        log2: "readonly",
        logScale: "readonly",
        main: "readonly",
        mods: "writable",
        openAudioFile: "readonly",
        openCushy: "readonly",
        papagenoUI: "readonly",
        random: "readonly",
        rescaleVolumeAndClipAdjust: "readonly",
        scale: "readonly",
        select: "readonly",
        selected: "readonly",
        signedSquare: "readonly",
        square: "readonly",
        toDecibel: "readonly",
        toMousePosition: "readonly",
        toggleCushy: "readonly",
        unescape: "readonly",

        // Bundled examples and JS Console keep persistent state in package
        // globals; external scripts can add their own /* global name:writable */.
        _: "writable",
        MyKnob: "writable",
        fourKnobs: "writable",
        genobatch: "writable",
        jsConsole: "writable",
        patchStack: "writable",
        skinChooser: "writable",
        tuningFork: "writable"
      }
    },
    rules: {
      "no-undef": "error",
      "no-restricted-syntax": [
        "error",
        {
          selector: "Property[kind='get'], Property[kind='set']",
          message: "Getter/setter object literal syntax is not supported by Synplant scripts."
        }
      ],
      "no-with": "error"
    }
  }
];
